name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: auth/requirements.txt
      - run: pip install -r requirements.txt
      - run: python -m unittest -v
